
var YilanDists = {
        'TP-Y100':              '頭城鎮',
        'TP-Y200':              '礁溪鄉',
        'TP-Y300':              '壯圍鄉',
        'TP-Y400':              '員山鄉',
        'TP-Y500':              '宜蘭市',
        'TP-Y600':              '大同鄉',
        'TP-Y700':              '五結鄉',
        'TP-Y800':              '三星鄉',
        'TP-Y900':              '羅東鎮',
        'TP-Y1000':             '冬山鄉',
        'TP-Y1100':             '南澳鄉',
        'TP-Y1200':             '蘇澳鎮',
};

var TaoyuanDists = {
        'TP-TY100':             '大園區',
        'TP-TY200':             '蘆竹區',
        'TP-TY300':             '觀音區',
        'TP-TY400':             '龜山區',
        'TP-TY500':             '桃園區',
        'TP-TY600':             '中壢區',
        'TP-TY700':             '新屋區',
        'TP-TY800':             '八德區',
        'TP-TY900':             '平鎮區',
        'TP-TY1000':            '楊梅區',
        'TP-Ty1100':            '大溪區',
        'TP-TY1200':            '龍潭區',
        'TP-TY1300':            '復興區',
};

var HsinchuDists = {
        'TP-HC100':             '新豐鄉',
        'TP-HC200':             '湖口鄉',
        'TP-HC300':             '新埔鎮',
        'TP-HC400':             '竹北市',
        'TP-HC500':             '關西鎮',
        'TP-HC600':             '芎林鄉',
        'TP-HC700':             '竹東鎮',
        'TP-HC800':             '寶山鄉',
        'TP-HC900':             '尖石鄉',
        'TP-HC1000':            '橫山鄉',
        'TP-HC1100':            '北埔鄉',
        'TP-HC1200':            '峨眉鄉',
        'TP-HC1300':            '五峰鄉',
};

var MiaoliDists = {
        'TP-ML100':             '竹南鎮',
        'TP-ML200':             '頭份市',
        'TP-ML300':             '三灣鄉',
        'TP-ML400':             '造橋鄉',
        'TP-ML500':             '後龍鎮',
        'TP-ML600':             '南庄鄉',
        'TP-ML700':             '頭屋鄉',
        'TP-ML800':             '獅潭鄉',
        'TP-ML900':             '苗栗市',
        'TP-ML1000':            '西湖鄉',
        'TP-ML1100':            '通霄鎮',
        'TP-ML1200':            '公館鄉',
        'TP-ML1300':            '銅鑼鄉',
        'TP-ML1400':            '泰安鄉',
        'TP-ML1500':            '苑裡鎮',
        'TP-ML1600':            '大湖鄉',
        'TP-ML1700':            '三義鄉',
        'TP-ML1800':            '卓蘭鎮',
};

var ChanghuaDists = {
        'TP-CH100':             '伸港鄉',
        'TP-CH200':             '和美鎮',
        'TP-CH300':             '線西鄉',
        'TP-CH400':             '鹿港鎮',
        'TP-CH500':             '彰化市',
        'TP-CH600':             '秀水鄉',
        'TP-CH700':             '福興鄉',
        'TP-CH800':             '花壇鄉',
        'TP-CH900':             '芬園鄉',
        'TP-CH1000':            '芳苑鄉',
        'TP-CH1100':            '埔鹽鄉',
        'TP-CH1200':            '大村鄉',
        'TP-CH1300':            '二林鎮',
        'TP-CH1400':            '員林市',
        'TP-CH1500':            '溪湖鎮',
        'TP-CH1600':            '埔心鄉',
        'TP-CH1700':            '永靖鄉',
        'TP-CH1800':            '社頭鄉',
        'TP-CH1900':            '埤頭鄉',
        'TP-CH2000':            '田尾鄉',
        'TP-CH2100':            '大城鄉',
        'TP-CH2200':            '田中鎮',
        'TP-CH2300':            '北斗鎮',
        'TP-CH2400':            '竹塘鄉',
        'TP-CH2500':            '溪州鄉',
        'TP-CH2600':            '二水鄉',
};

var NantouDists = {
        'TP-NT100':             '仁愛鄉',
        'TP-NT200':             '國姓鄉',
        'TP-NT300':             '埔里鎮',
        'TP-NT400':             '草屯鎮',
        'TP-NT500':             '中寮鄉',
        'TP-NT600':             '南投市',
        'TP-NT700':             '魚池鄉',
        'TP-NT800':             '水里鄉',
        'TP-NT900':             '名間鄉',
        'TP-NT1000':            '信義鄉',
        'TP-NT1100':            '集集鎮',
        'TP-NT1200':            '竹山鎮',
        'TP-NT1300':            '鹿谷鄉',
};


var YunlinDists = {
        'TP-YL100':             '麥寮鄉',
        'TP-YL200':             '二崙鄉',
        'TP-YL300':             '崙背鄉',
        'TP-YL400':             '西螺鎮',
        'TP-YL500':             '莿桐鄉',
        'TP-YL600':             '林內鄉',
        'TP-YL700':             '臺西鄉',
        'TP-YL800':             '土庫鎮',
        'TP-YL900':             '虎尾鎮',
        'TP-YL1000':            '褒忠鄉',
        'TP-YL1100':            '東勢鄉',
        'TP-YL1200':            '斗南鎮',
        'TP-YL1300':            '四湖鄉',
        'TP-YL1400':            '古坑鄉',
        'TP-YL1500':            '元長鄉',
        'TP-YL1600':            '大埤鄉',
        'TP-YL1700':            '口湖鄉',
        'TP-YL1800':            '北港鎮',
        'TP-YL1900':            '水林鄉',
        'TP-YL2000':            '斗六市',
};

var ChiayiDists = {
        'TP-CY100':             '大林鎮',
        'TP-CY200':             '溪口鄉',
        'TP-CY300':             '阿里山鄉',
        'TP-CY400':             '新港鄉',
        'TP-CY500':             '民雄鄉',
        'TP-CY600':             '六腳鄉',
        'TP-CY700':             '竹崎鄉',
        'TP-CY800':             '東石鄉',
        'TP-CY900':             '太保市',
        'TP-CY1000':            '番路鄉',
        'TP-CY1100':            '水上鄉',
        'TP-CY1200':            '中埔鄉',
        'TP-CY1300':            '布袋鎮',
        'TP-CY1400':            '鹿草鄉',
        'TP-CY1500':            '義竹鄉',
        'TP-CY1600':            '大埔鄉',
};

var PingtungDists = {
        'TP-PT100':             '高樹鄉',
        'TP-PT200':             '三地門鄉',
        'TP-PT300':             '霧臺鄉',
        'TP-PT400':             '里港鄉',
        'TP-PT500':             '鹽埔鄉',
        'TP-PT600':             '九如鄉',
        'TP-PT700':             '長治鄉',
        'TP-PT800':             '瑪家鄉',
        'TP-PT900':             '屏東市',
        'TP-PT1000':            '內埔鄉',
        'TP-PT1100':            '麟洛鄉',
        'TP-PT1200':            '泰武鄉',
        'TP-PT1300':            '萬巒鄉',
        'TP-PT1400':            '萬丹鄉',
        'TP-PT1500':            '來義鄉',
        'TP-PT1600':            '潮州鎮',
        'TP-PT1700':            '新園鄉',
        'TP-PT1800':            '崁頂鄉',
        'TP-PT1900':            '新埤鄉',
        'TP-PT2000':            '南州鄉',
        'TP-PT2100':            '東港鎮',
        'TP-PT2200':            '林邊鄉',
        'TP-PT2300':            '佳冬鄉',
        'TP-PT2400':            '春日鄉',
        'TP-PT2500':            '獅子鄉',
        'TP-PT2600':            '琉球鄉',
        'TP-PT2700':            '枋山鄉',
        'TP-PT2800':            '牡丹鄉',
        'TP-PT2900':            '滿州鄉',
        'TP-PT3000':            '車城鄉',
        'TP-PT3100':            '恆春鎮',
        'TP-PT3200':            '枋寮鄉',
};

var TaitungDists = {
        'TP-TT100':             '長濱鄉',
        'TP-TT200':             '海端鄉',
        'TP-TT300':             '池上鄉',
        'TP-TT400':             '成功鎮',
        'TP-TT500':             '關山鎮',
        'TP-TT600':             '東河鄉',
        'TP-TT700':             '鹿野鄉',
        'TP-TT800':             '延平鄉',
        'TP-TT900':             '卑南鄉',
        'TP-TT1000':            '臺東市',
        'TP-TT1100':            '太麻里鄉',
        'TP-TT1200':            '綠島鄉',
        'TP-TT1300':            '達仁鄉',
        'TP-TT1400':            '大武鄉',
        'TP-TT1500':            '蘭嶼鄉',
        'TP-TT1600':            '金峰鄉',
};

var HualienDists = {
        'TP-HL100':             '秀林鄉',
        'TP-HL200':             '新城鄉',
        'TP-HL300':             '花蓮市',
        'TP-HL400':             '吉安鄉',
        'TP-HL500':             '壽豐鄉',
        'TP-HL600':             '萬榮鄉',
        'TP-HL700':             '鳳林鎮',
        'TP-HL800':             '豐濱鄉',
        'TP-HL900':             '光復鄉',
        'TP-HL1000':            '卓溪鄉',
        'TP-HL1100':            '瑞穗鄉',
        'TP-HL1200':            '玉里鎮',
        'TP-HL1300':            '富里鄉',
};

var PenghuDists = {
        'TP-PH100':             '白沙鄉',
        'TP-PH200':             '西嶼鄉',
        'TP-PH300':             '湖西鄉',
        'TP-PH400':             '馬公市',
        'TP-PH500':             '望安鄉',
        'TP-PH600':             '七美鄉',
};

var KeelungDists = {
        'TP-KL100':             '安樂區',
        'TP-KL200':             '中山區',
        'TP-KL300':             '中正區',
        'TP-KL400':             '七堵區',
        'TP-KL500':             '信義區',
        'TP-KL600':             '仁愛區',
        'TP-KL700':             '暖暖區',
};

var HsinchuCDists = {
        'TP-HCC100':            '北區',
        'TP-HCC200':            '香山區',
        'TP-HCC300':            '東區',       
};

var ChiayiCDists = {
        'TP-CYC100':            '西區',
        'TP-CYC200':            '東區',
       
};

var TaipeiCDists = {
        'TP-TPC100':            '北投區',
        'TP-TPC200':            '士林區',
        'TP-TPC300':            '內湖區',
        'TP-TPC400':            '中山區',
        'TP-TPC500':            '大同區',
        'TP-TPC600':            '松山區',
        'TP-TPC700':            '南港區',
        'TP-TPC800':            '中正區',
        'TP-TPC900':            '萬華區',
        'TP-TPC1000':           '信義區',
        'TP-TPC1100':           '大安區',
        'TP-TPC1200':           '文山區',
};

var KaohsiungCDists = {
       
        'TP-KHC100':             '楠梓區',
        'TP-KHC200':             '左營區',
        'TP-KHC300':             '三民區',
        'TP-KHC400':             '鼓山區',
        'TP-KHC500':             '苓雅區',
        'TP-KHC600':             '新興區',
        'TP-KHC700':             '前金區',
        'TP-KHC800':             '鹽埕區',
        'TP-KHC900':             '前鎮區',
        'TP-KHC1000':            '旗津區',
        'TP-KHC1100':            '小港區',
        'TP-KHC1200':            '那瑪夏區',
        'TP-KHC1300':            '甲仙區',
        'TP-KHC1400':            '六龜區',
        'TP-KHC1500':            '杉林區',
        'TP-KHC1600':            '內門區',
        'TP-KHC1700':            '茂林區',
        'TP-KHC1800':            '美濃區',
        'TP-KHC1900':            '旗山區',
        'TP-KHC2000':            '田寮區',
        'TP-KHC2100':            '湖內區',
        'TP-KHC2200':            '茄萣區',
        'TP-KHC2300':            '阿蓮區',
        'TP-KHC2400':            '路竹區',
        'TP-KHC2500':            '永安區',
        'TP-KHC2600':            '岡山區',
        'TP-KHC2700':            '燕巢區',
        'TP-KHC2800':            '彌陀區',
        'TP-KHC2900':            '橋頭區',
        'TP-KHC3000':            '大樹區',
        'TP-KHC3100':            '梓官區',
        'TP-KHC3200':            '大社區',
        'TP-KHC3300':            '仁武區',
        'TP-KHC3400':            '鳥松區',
        'TP-KHC3500':            '大寮區',
        'TP-KHC3600':            '鳳山區',
        'TP-KHC3700':            '林園區',
        'TP-KHC3800':            '桃源區',
};

var NewTaipeiCDists = {
        'TP-NTPC100':             '石門區',
        'TP-NTPC200':             '三芝區',
        'TP-NTPC300':             '金山區',
        'TP-NTPC400':             '淡水區',
        'TP-NTPC500':             '萬里區',
        'TP-NTPC600':             '八里區',
        'TP-NTPC700':             '汐止區',
        'TP-NTPC800':             '林口區',
        'TP-NTPC900':             '五股區',
        'TP-NTPC1000':            '瑞芳區',
        'TP-NTPC1100':            '蘆洲區',
        'TP-NTPC1200':            '雙溪區',
        'TP-NTPC1300':            '三重區',
        'TP-NTPC1400':            '貢寮區',
        'TP-NTPC1500':            '平溪區',
        'TP-NTPC1600':            '泰山區',
        'TP-NTPC1700':            '新莊區',
        'TP-NTPC1800':            '石碇區',
        'TP-NTPC1900':            '板橋區',
        'TP-NTPC2000':            '深坑區',
        'TP-NTPC2100':            '永和區',
        'TP-NTPC2200':            '樹林區',
        'TP-NTPC2300':            '中和區',
        'TP-NTPC2400':            '土城區',
        'TP-NTPC2500':            '新店區',
        'TP-NTPC2600':            '坪林區',
        'TP-NTPC2700':            '鶯歌區',
        'TP-NTPC2800':            '三峽區',
        'TP-NTPC2900':            '烏來區',
};

var TaichungCDists = {
        'TP-TCC100':     '北屯區',
        'TP-TCC200':     '西屯區',
        'TP-TCC300':     '北區',
        'TP-TCC400':     '南屯區',
        'TP-TCC500':     '西區',
        'TP-TCC600':     '東區',
        'TP-TCC700':     '中區',
        'TP-TCC800':     '南區',
        'TP-TCC900':     '和平區',
        'TP-TCC1000':    '大甲區',
        'TP-TCC1100':    '大安區',
        'TP-TCC1200':    '外埔區',
        'TP-TCC1300':    '后里區',
        'TP-TCC1400':    '清水區',
        'TP-TCC1500':    '東勢區',
        'TP-TCC1600':    '神岡區',
        'TP-TCC1700':    '龍井區',
        'TP-TCC1800':    '石岡區',
        'TP-TCC1900':    '豐原區',
        'TP-TCC2000':    '梧棲區',
        'TP-TCC2100':    '新社區',
        'TP-TCC2200':    '沙鹿區',
        'TP-TCC2300':    '大雅區',
        'TP-TCC2400':    '潭子區',
        'TP-TCC2500':    '大肚區',
        'TP-TCC2600':    '太平區',
        'TP-TCC2700':    '烏日區',
        'TP-TCC2800':    '大里區',
        'TP-TCC2900':    '霧峰區',
};

var TainanCDists = {
        'TP-TNC100':            '安南區',
        'TP-TNC200':            '中西區',
        'TP-TNC300':            '安平區',
        'TP-TNC400':            '東區',
        'TP-TNC500':            '南區',
        'TP-TNC600':            '北區',
        'TP-TNC700':            '白河區',
        'TP-TNC800':            '後壁區',
        'TP-TNC900':            '鹽水區',
        'TP-TNC1000':           '新營區',
        'TP-TNC1100':           '東山區',
        'TP-TNC1200':           '北門區',
        'TP-TNC1300':           '柳營區',
        'TP-TNC1400':           '學甲區',
        'TP-TNC1500':           '下營區',
        'TP-TNC1600':           '六甲區',
        'TP-TNC1700':           '南化區',
        'TP-TNC1800':           '將軍區',
        'TP-TNC1900':           '楠西區',
        'TP-TNC2000':           '麻豆區',
        'TP-TNC2100':           '官田區',
        'TP-TNC2200':           '佳里區',
        'TP-TNC2300':           '大內區',
        'TP-TNC2400':           '七股區',
        'TP-TNC2500':           '玉井區',
        'TP-TNC2600':           '善化區',
        'TP-TNC2700':           '西港區',
        'TP-TNC2800':           '山上區',
        'TP-TNC2900':           '安定區',
        'TP-TNC3000':           '新市區',
        'TP-TNC3100':           '左鎮區',
        'TP-TNC3200':           '新化區',
        'TP-TNC3300':           '永康區',
        'TP-TNC3400':           '歸仁區',
        'TP-TNC3500':           '關廟區',
        'TP-TNC3600':           '龍崎區',
        'TP-TNC3700':           '仁德區',
};

var LianjiangDists = {
        'TP-LJC100':      '南竿鄉',
        'TP-LJC200':      '北竿鄉',
        'TP-LJC300':      '莒光鄉',
        'TP-LJC400':      '東引鄉',
};

var KinmenDists = {
        'TP-KM100':      '金城鎮',
        'TP-KM200':      '金湖鎮',
        'TP-KM300':      '金沙鎮',
        'TP-KM400':      '金寧鄉',
        'TP-KM500':      '烈嶼鄉',
        'TP-KM600':      '烏坵鄉',
};

var     districtInfos   = function (cityCode) {
        let distsInfosMap = {
                'F-D0047-001':          YilanDists,
                'F-D0047-005':          TaoyuanDists,
                'F-D0047-009':          HsinchuDists,
                'F-D0047-013':          MiaoliDists,
                'F-D0047-017':          ChanghuaDists,
                'F-D0047-021':          NantouDists,
                'F-D0047-025':          YunlinDists,
                'F-D0047-029':          ChiayiDists,
                'F-D0047-033':          PingtungDists,
                'F-D0047-037':          TaitungDists,
                'F-D0047-041':          HualienDists,
                'F-D0047-045':          PenghuDists,
                'F-D0047-049':          KeelungDists,
                'F-D0047-053':          HsinchuCDists,
                'F-D0047-057':          ChiayiCDists,
                'F-D0047-061':          TaipeiCDists,
                'F-D0047-065':          KaohsiungCDists,
                'F-D0047-069':          NewTaipeiCDists,
                'F-D0047-073':          TaichungCDists,
                'F-D0047-077':          TainanCDists,
                'F-D0047-081':          LianjiangDists,
                'F-D0047-085':          KinmenDists,
        };

        return distsInfosMap.hasOwnProperty (cityCode) ? distsInfosMap[cityCode] : {}
};


var     cityInfos           = function () {
         
        let     cityInfosMap   = {
               'F-D0047-001': { label: '宜蘭縣', dataid: 'F-D0047-001' },
               'F-D0047-005': { label: '桃園市', dataid: 'F-D0047-005' },
               'F-D0047-009': { label: '新竹縣', dataid: 'F-D0047-009' },
               'F-D0047-013': { label: '苗栗縣', dataid: 'F-D0047-013' },
               'F-D0047-017': { label: '彰化縣', dataid: 'F-D0047-017' },
               'F-D0047-021': { label: '南投縣', dataid: 'F-D0047-021' },
               'F-D0047-025': { label: '雲林縣', dataid: 'F-D0047-025' },
               'F-D0047-029': { label: '嘉義縣', dataid: 'F-D0047-029' },
               'F-D0047-033': { label: '屏東縣', dataid: 'F-D0047-033' },
               'F-D0047-037': { label: '台東縣', dataid: 'F-D0047-037' },
               'F-D0047-041': { label: '花蓮縣', dataid: 'F-D0047-041' },
               'F-D0047-045': { label: '澎湖縣', dataid: 'F-D0047-045' },
               'F-D0047-049': { label: '基隆市', dataid: 'F-D0047-049' },
               'F-D0047-053': { label: '新竹市', dataid: 'F-D0047-053' },
               'F-D0047-057': { label: '嘉義市', dataid: 'F-D0047-057' },
               'F-D0047-061': { label: '台北市', dataid: 'F-D0047-061' },
               'F-D0047-065': { label: '高雄市', dataid: 'F-D0047-065' },
               'F-D0047-069': { label: '新北市', dataid: 'F-D0047-069' },
               'F-D0047-073': { label: '台中市', dataid: 'F-D0047-073' },
               'F-D0047-077': { label: '台南市', dataid: 'F-D0047-077' },
               'F-D0047-081': { label: '連江縣', dataid: 'F-D0047-081' },
               'F-D0047-085': { label: '金門縣', dataid: 'F-D0047-085' },
        };

        return Object.values(cityInfosMap)
        // return cityInfosMap.hasOwnProperty (cityCode) ? cityInfosMap[cityCode] : cityInfosMap
}

export default {
        districtInfos,
        cityInfos,
}